
/*
======================================================
DDL Script: Creating silver Tables
======================================================
Script Purpose: 
   This script creates tables in the 'silver' schema, dropping existing tables if they already exist. 
  run this script to re-define the DDL structure of 'silver' Tables
=======================================================
*/


IF Object_ID ('Hope_silver' , 'U') IS NOT NULL
	DROP TABLE Hope_silver;


CREATE TABLE Hope_silver (
    [Application Id] NVARCHAR(MAX),
    [Household Id] NVARCHAR(MAX),
    [Person Id] NVARCHAR(MAX),
    [First Name] NVARCHAR(MAX),
    [Last Name HCLIC A1.5] NVARCHAR(MAX),
    [NINO HCLIC A1.6] NVARCHAR(MAX),
    [Email Address] NVARCHAR(MAX),
    [Mobile Number] NVARCHAR(MAX),
    [Date of Birth HCLIC A1.3] NVARCHAR(MAX),
    [Sex HCLIC 2.3] NVARCHAR(MAX),
    [Relationship HCLIC -2.5] NVARCHAR(MAX),
    [Age at Application(HCLIC - 2.4)] NVARCHAR(MAX),
    [Age on Quarter End(HCLIC -2.8)] NVARCHAR(MAX),
    [Date Of Submission] NVARCHAR(MAX),
    [Assigned To] NVARCHAR(MAX),
    [Date Joined(HCLIC -2.6)] NVARCHAR(MAX),
    [Address (HCLIC A1.7)] NVARCHAR(MAX),
    [PostCode (HCLIC A1.8)] NVARCHAR(MAX),
    [Address Type] NVARCHAR(MAX),
    [Date Move In] NVARCHAR(MAX),
    [Date Move Out] NVARCHAR(MAX),
    [App Type] NVARCHAR(MAX),
    [Plan Type] NVARCHAR(MAX),
    [Plan Created Date] NVARCHAR(MAX),
    [Plan Publish Status] NVARCHAR(MAX),
    [Is the applicant working?] NVARCHAR(MAX),
    [Has the applicant ever worked?] NVARCHAR(MAX),
    [Reason for no longer working] NVARCHAR(MAX),
    [What is the applicants average weekly hours and income?] NVARCHAR(MAX),
    [Has the applicant been granted refugee status in the uk?] NVARCHAR(MAX),
    [Has the applicant been given any leave to remain whether limited or Indefinite leave to remain with Recource to public funds?] NVARCHAR(MAX),
    [Is the applicant primary carer of a British national?] NVARCHAR(MAX),
    [Has the applicant got Indefinite or limited or Exceptional Leave to Enter or Remain in the UK with no immigration restrict] NVARCHAR(MAX),
    [Is the applicant self-employed?] NVARCHAR(MAX),
    [Has the applicant been posted here by an EU company on a temporary basis to provide services on behalf of an undertaking] NVARCHAR(MAX),
    [Reason why the applicant is not eligible?] NVARCHAR(MAX),
    [Is the applicant only in the UK as a job seeker?] NVARCHAR(MAX),
    [Worker - is the work genuine and effective and not marginal and ancillary?] NVARCHAR(MAX),
    [Reason for no longer working - Others] NVARCHAR(MAX),
    [What was the applicants average weekly hours and income?] NVARCHAR(MAX),
    [Worker - was the work genuine and effective and not marginal and ancillary?] NVARCHAR(MAX),
    [Is the applicant engaging in self-employment?] NVARCHAR(MAX),
    [Has the applicant ever been self-employed?] NVARCHAR(MAX),
    [Reason for no longer being self-employed] NVARCHAR(MAX),
    [What was the applicants average weekly hours & income?] NVARCHAR(MAX),
    [Self-employed - was the work genuine and effective and not marginal and ancillary?] NVARCHAR(MAX),
    [Applicant is the citizen of which country?] NVARCHAR(MAX),
    [Is the applicant Self sufficient with comprehensive sickness insurance?] NVARCHAR(MAX),
    [Is the applicant a student and self sufficient with comprehensive sickness insurance?] NVARCHAR(MAX),
    [Is the applicant a family member of an EEA national exercising their EU right in the UK] NVARCHAR(MAX),
    [Is the EEA national a worker or self employed?] NVARCHAR(MAX),
    [Is the EEA national a job seeker or self-sufficient?] NVARCHAR(MAX),
    [Does the applicant have a Derivative right?] NVARCHAR(MAX),
    [Does the applicant have a right to reside permanently in the UK?] NVARCHAR(MAX),
    [What is applicants average weekly hours and income?] NVARCHAR(MAX),
    [Worker: is the work genuine and effective and not marginal and ancillary?] NVARCHAR(MAX),
    [Reason for no longer being self-employed - Others] NVARCHAR(MAX),
    [Are they habitually resident in the UK?] NVARCHAR(MAX),
    [Please select the relationship?] NVARCHAR(MAX),
    [Please provide details of dependants] NVARCHAR(MAX),
    [What is the applicant average weekly hours and income?] NVARCHAR(MAX),
    [Is the work genuine and effective and not marginal and ancillary?] NVARCHAR(MAX),
    [Reason for no longer working or self-employed] NVARCHAR(MAX),
    [Reason for no longer working-Others] NVARCHAR(MAX),
    [What was the average weekly hours and income?] NVARCHAR(MAX),
    [Was the work genuine and effective and not marginal and ancillary?] NVARCHAR(MAX),
    [Please select the reason for Derivative right?] NVARCHAR(MAX),
    [Please select the reason for applicant's right to reside permanently in the UK?] NVARCHAR(MAX),
    [Did the applicant work lawfully in the UK for 12 months prior to 1 July 2013?] NVARCHAR(MAX),
    [Please select the relationship] NVARCHAR(MAX),
    [Please provide details of dependant's] NVARCHAR(MAX),
    [How long is the applicants most recent period of residence in the UK?] NVARCHAR(MAX),
    [Are they returning to resume a previous period of residence in the UK?] NVARCHAR(MAX),
    [Did the applicant enter the UK under the Highly Skilled Migrants programme and are Working?] NVARCHAR(MAX),
    [Did the applicant enter the UK as a low skill worker and are working in agriculture and food processing?] NVARCHAR(MAX),
    [Was the applicant a low skill worker and working in agriculture and food processing for 12 months?] NVARCHAR(MAX),
    [Is the applicant a family member of an EEA national exercising their EU right in the UK?] NVARCHAR(MAX),
    [Are you satisfied that the applicant is homeless?] NVARCHAR(MAX),
    [Being evicted by Housing Association (add details if this is a relevant issue)] NVARCHAR(MAX),
    [Being evicted by Council (add details if this is a relevant issue)] NVARCHAR(MAX),
    [Being evicted by Family / Friends (add details if this is a relevant issue)] NVARCHAR(MAX),
    [Being evicted by Private Landlord (add details if this is a relevant issue)] NVARCHAR(MAX),
    [Being evicted by resident landlord (add details if this is a relevant issue)] NVARCHAR(MAX),
    [Being evicted by employer (add details if this is a relevant issue)] NVARCHAR(MAX),
    [Overcrowded (add details if this is a relevant issue)] NVARCHAR(MAX),
    [Condition / disrepair (add details if this is a relevant issue)] NVARCHAR(MAX),
    [Threat of violence (add details if this is a relevant issue)] NVARCHAR(MAX),
    [Not affordable (add details if this is a relevant issue)] NVARCHAR(MAX),
    [Does the applicant have accommodation available to them in UK or elsewhere? ] NVARCHAR(MAX),
    [Medical issues (add details if this is a relevant issue)] NVARCHAR(MAX),
    [Other reason (add details if this is a relevant issue)] NVARCHAR(MAX),
    [Is the applicant being evicted from accommodation that is otherwise available and reasonable to continue to occupy?] NVARCHAR(MAX),
    [Pending leave date ] NVARCHAR(MAX),
    [Reason for leaving ] NVARCHAR(MAX),
    [Type of eviction] NVARCHAR(MAX),
    [Is the applicant or a member of the household currently at risk of abuse, violence or harassement?] NVARCHAR(MAX),
    [Name of the Victim] NVARCHAR(MAX),
    [Do they know the perpetrator?] NVARCHAR(MAX),
    [Name of Perpetrator] NVARCHAR(MAX),
    [Is this domestic violence from partner?] NVARCHAR(MAX),
    [Is this violence from outside the home?] NVARCHAR(MAX),
    [Does the applicant consider the accommodation reasonable to continue to occupy?] NVARCHAR(MAX),
    [Type of Violence / Harassment] NVARCHAR(MAX),
    [Does the authority consider the accommodation reasonable to continue to occupy?] NVARCHAR(MAX),
    [Does the applicant have to leave within 56 days?] NVARCHAR(MAX),
    [Has the applicant been served with a Section 21 notice within 56 days?] NVARCHAR(MAX),
    [Is the applicant withholding information in relation to their homelessness?] NVARCHAR(MAX),
    [If applicant does not feel accommodation is reasonable, what is the reason for this? ] NVARCHAR(MAX),
    [Please tell us why the accommodation is no longer available? ] NVARCHAR(MAX),
    [Officer's Decision: Reasonable accommodation?] NVARCHAR(MAX),
    [Reason for decision] NVARCHAR(MAX),
    [Before getting the s.21 notice, did the tenant make a complaint about the condition of the property to the landlord, in writing] NVARCHAR(MAX),
    [Does the S.21 notice form look exactly like the Form 6A here (or to substantially the same effect)] NVARCHAR(MAX),
    [Tenancy in a House of Multiple Occupation that requires licensing under Mandatory licensing, or the Local Authorities] NVARCHAR(MAX),
    [Was a deposit taken for the tenancy before 6 April 2007?] NVARCHAR(MAX),
    [Have there been any new tenancy agreements since 6 April 2007] NVARCHAR(MAX),
    [Has the deposit been protected in a deposit scheme?] NVARCHAR(MAX),
    [Was a deposit taken?] NVARCHAR(MAX),
    [Did current tenancy agreement start on or after 1 October 2015?] NVARCHAR(MAX),
    [Was the deposit protected in a scheme at any time and still protected? (if not paid back to tenant before s.21 notice)] NVARCHAR(MAX),
    [Was the ‘prescribed information’ given in full at any time?] NVARCHAR(MAX),
    [Is this the first tenancy agreement for the property?] NVARCHAR(MAX),
    [Was the deposit protected in a scheme within 30 days of being received?] NVARCHAR(MAX),
    [Was the deposit protected and prescribed information served during a previous tenancy agreement for the same property?] NVARCHAR(MAX),
    [Was the deposit protected and prescribed information served within 30 days of the deposit being taken?] NVARCHAR(MAX),
    [Was the deposit protected in an approved scheme within 30 days of being taken?] NVARCHAR(MAX),
    [Was the prescribed information given to the tenant before or at the same time as the section 21 notice] NVARCHAR(MAX),
    [Does the Section 21 Notice give at least two months notice AND date given is at end at or after the end of the fixed term?] NVARCHAR(MAX),
    [Does the Section 21 Notice give at least two months notice AND date given if is at end at or after the end of the fixed term?] NVARCHAR(MAX),
    [Has the tenant received: Gas safety certificate dated in last 12 months (if gas supply) Government ‘How to Rent’ Booklet?] NVARCHAR(MAX),
    [Is the tenancy of a room in a house in multiple occupation with shared facilities?] NVARCHAR(MAX),
    [Has the tenant received an energy Performance Certificate for the flat/house] NVARCHAR(MAX),
    [Was the section 21 notice served less than 4 months from the start of the tenancy] NVARCHAR(MAX),
    [Does it give at least 2 months notice?] NVARCHAR(MAX),
    [Was the section 21 notice served more than 6 months ago] NVARCHAR(MAX),
    [Has the Council served an Improvement Notice or Emergency Remedial Notice about the property in the last 6 months?] NVARCHAR(MAX),
    [Is a temporary accommodation duty owed during the prevention duty?] NVARCHAR(MAX),
    [Prevention Review Date] NVARCHAR(MAX),
    [Is the applicant failing to cooperate?] NVARCHAR(MAX),
    [Does the authority wish to end the prevention duty on the basis of ‘Refused to cooperate’?] NVARCHAR(MAX),
    [Has this decision been signed off by an appropriate person?] NVARCHAR(MAX),
    [PREV- Does the applicant agree with the plan?If yes,issue a prevention duty notification letter with a copy of the personal plan] NVARCHAR(MAX),
    [Please provide details of the appropriate person] NVARCHAR(MAX),
    [applicant disagrees with the plan? If no, issue a prevention duty notification letter with a copy of the personal plan] NVARCHAR(MAX),
    [Circumstances that caused the applicant to become homeless or threatened with homelessness] NVARCHAR(MAX),
    [Housing Needs of the applicant] NVARCHAR(MAX),
    [Housing Wishes of the applicant] NVARCHAR(MAX),
    [Support needs of the applicant to acquire and maintain accommodation] NVARCHAR(MAX),
    [Do you have reasons to believe the applicant is eligible?] NVARCHAR(MAX),
    [Please provide reasons to believe that applicant is eligible] NVARCHAR(MAX),
    [Do you have reasons to believe the applicant is Homeless?] NVARCHAR(MAX),
    [Please provide reasons to believe that applicant is Homeless] NVARCHAR(MAX),
    [Do you have reasons to believe that applicant has a priority need?] NVARCHAR(MAX),
    [Please provide reasons to believe that applicant has a priority need] NVARCHAR(MAX),
    [Temporary accommodation provided?] NVARCHAR(MAX),
    [Do you wish to make a final accommodation offer ] NVARCHAR(MAX),
    [Does the applicant consider the accommodation they have accepted unsuitable ] NVARCHAR(MAX),
    [Does the authority consider the accommodation suitable ] NVARCHAR(MAX),
    [Do you wish to make a final part 6 offer ] NVARCHAR(MAX),
    [Do you wish to end the relief duty because the applicant has refused a final part 6 offer ] NVARCHAR(MAX),
    [Does the authority wish to end the relief duty on the basis of refused to cooperate ] NVARCHAR(MAX),
    [Has this decision been signed off by an appropriate person] NVARCHAR(MAX),
    [please provide details of the appropriate person.] NVARCHAR(MAX),
    [Do you wish to end the relief duty because the applicant has refused a final accommodation offer] NVARCHAR(MAX),
    [Relief Review Date] NVARCHAR(MAX),
    [Does the applicant have any preference as to where they would like to live?] NVARCHAR(MAX),
    [Is there a particular type of accommodation will meet the applicant and his/her households needs?] NVARCHAR(MAX),
    [Supported Hostel] NVARCHAR(MAX),
    [REL- Does the applicant agree with the plan?] NVARCHAR(MAX),
    [If the applicant disagrees with the plan give reasons why] NVARCHAR(MAX),
    [Circumstances that caused the applicant to become homeless] NVARCHAR(MAX),
    [Housing Needs of the applicant.] NVARCHAR(MAX),
    [Housing Wishes of the applicant.] NVARCHAR(MAX),
    [Support needs of the applicant to acquire and maintain accommodation. ] NVARCHAR(MAX),
    [Does the applicant have residency in the district 6 out of the last 12 months or 3 out of the last 5 years?] NVARCHAR(MAX),
    [Give Details] NVARCHAR(MAX),
    [Is the applicant under 21 and is provided accommodation under section 22(a) of the Children Act 1989?] NVARCHAR(MAX),
    [Do they have a local connection with another Authority] NVARCHAR(MAX),
    [Please provide reason.] NVARCHAR(MAX),
    [Will they run the risk of violence in that district?] NVARCHAR(MAX),
    [Are you satisfied that the applicant is eligible for local connection?] NVARCHAR(MAX),
    [Please provide reason for local connection] NVARCHAR(MAX),
    [Is the applicant employed in the district] NVARCHAR(MAX),
    [Please provide reason for district?] NVARCHAR(MAX),
    [Does the applicant have family association living in the district in the last 5 years?] NVARCHAR(MAX),
    [Please provide reasons] NVARCHAR(MAX),
    [Does the applicant have any special circumstances?] NVARCHAR(MAX),
    [Please provide reason for special circumstances] NVARCHAR(MAX),
    [Is the applicant a duty under section 23(c) of the Children Act 1989] NVARCHAR(MAX),
    [Is the applicant in any of the priority need groups?] NVARCHAR(MAX),
    [Pregnancy - is the applicant or member of the household pregnant?] NVARCHAR(MAX),
    [Dependant children – below the age of 16 or aged 16-18, who is dependent and either normally resident] NVARCHAR(MAX),
    [16 and 17 year olds - Is there a child, 16 or 17 years old and who is not a ‘relevant child’ or a child in need] NVARCHAR(MAX),
    [looked after, accommodated or fostered - Applicant is not a person who is aged 18 to 20 and was formerly looked after] NVARCHAR(MAX),
    [Emergency - The Applicant is homeless because of an emergency such as fire, flood, or a similar disaster?] NVARCHAR(MAX),
    [Vulnerability - Applicant is vulnerable as the result of List following heading if relevant to QA] NVARCHAR(MAX),
    [Household intentionally homeless?] NVARCHAR(MAX),
    [Does the applicant feel that the accommodation was reasonable to continue to occupy] NVARCHAR(MAX),
    [Does the applicant feel that their actions were the result of inability to manage their own affairs or mental illness] NVARCHAR(MAX),
    [If the section 193a Temporary Accommodation duty is not owed, where is the applicant living?] NVARCHAR(MAX),
    [What was the applicant's accommodation when section 193(2), section 193C(4) or the section 195A(1) duty ended?] NVARCHAR(MAX),
    [Does the applicant have residency in the district 6 out of the last 12 months or 3 out of the last 5 years] NVARCHAR(MAX),
    [Please Give details] NVARCHAR(MAX),
    [applicant under 21 and is provided accommodation under section 22(a) Children Act 1989 and has resided for the last 2 years?] NVARCHAR(MAX),
    [Do they have a local connection with another authority?] NVARCHAR(MAX),
    [Please provide reason] NVARCHAR(MAX),
    [Will they run the risk of violence in that district] NVARCHAR(MAX),
    [Do you wish to refer the relief duty to another local authority?] NVARCHAR(MAX),
    [Are you satisfied that the applicant is eligible for local connection] NVARCHAR(MAX),
    [Please provide the reason] NVARCHAR(MAX),
    [Is the applicant employed in the district?] NVARCHAR(MAX),
    [Please provide a reason] NVARCHAR(MAX),
    [Does the applicant have family association living in the district?] NVARCHAR(MAX),
    [Please provide reason also.] NVARCHAR(MAX),
    [Does the applicant have any special circumstances] NVARCHAR(MAX),
    [Please provide reason for circumstances] NVARCHAR(MAX),
    [Is the applicant owed a duty under section 23(c) of the Children Act 1989?] NVARCHAR(MAX),
    [Household Member Description] NVARCHAR(MAX),
    [ApplicantÂ Date started] NVARCHAR(MAX),
    [ partner/spouse ApplicantÂ Date started] NVARCHAR(MAX),
    [Â partner/spouse Description ] NVARCHAR(MAX),
    [If unemployed, has the applicant or a member of the household ever worked in the UK?] NVARCHAR(MAX),
    [Enter dates last worked] NVARCHAR(MAX),
    [Date received] NVARCHAR(MAX),
    [Employment status of the main applicant] NVARCHAR(MAX),
    [Referred into another authority] NVARCHAR(MAX),
    [Does the applicant or a member of the household have any support needs?] NVARCHAR(MAX),
    [Does anyone help the person with their support needs?] NVARCHAR(MAX),
    [H-CLIC 1.1 Local Authority Code and Case Reference Number ] NVARCHAR(MAX),
    [H-CLIC 1.3 Are you satisfied that the applicant is eligible for assistance?] NVARCHAR(MAX),
    [H-CLIC 1.4 Number of Children] NVARCHAR(MAX),
    [H-CLIC 1.5 Date of assessment] NVARCHAR(MAX),
   
    [H-CLIC 1.6 What duties are owed to the applicant?] NVARCHAR(MAX),
    [H-CLIC 1.7 Ethnic Group of the main applicant] NVARCHAR(MAX),
    [H-CLIC 1.8 Sexual Preference of the main applicant] NVARCHAR(MAX),
    [H-CLIC 1.9 What is the nationality of the main applicant?] NVARCHAR(MAX),
    [H-CLIC 1.10 Current employment status for applicant] NVARCHAR(MAX),
    [H-CLIC 1.11 Is anyone in the household claiming benefits towards housing costs?] NVARCHAR(MAX),
    [H-CLIC 1.12 Is anyone in the household claiming benefits towards other living costs?] NVARCHAR(MAX),
    [H-CLIC 1.13 Please give details of current address] NVARCHAR(MAX),
    [H-CLIC 1.14 Last settled accommodation type] NVARCHAR(MAX),
    [H-CLIC 1.15 Main reason for loss of settled home] NVARCHAR(MAX),
    [H-CLIC 1.16 what was the reason for the loss of private tenancy (Assured Shorthold Tenancy)?] NVARCHAR(MAX),
    [H-CLIC 1.17 what was the reason for the loss of social rented tenancy?] NVARCHAR(MAX),
    [H-CLIC 1.18 what was the reason for the eviction from supported housing?] NVARCHAR(MAX),
    [H-CLIC 1.19 Whether applicant referred to the authority?] NVARCHAR(MAX),
    [H-CLIC 1.20 Agency type] NVARCHAR(MAX),
    [H-CLIC 1.21 Referred by another authority] NVARCHAR(MAX),
    [H-CLIC 1.22 Date homeless application made] NVARCHAR(MAX),
    [H-CLIC 1.23 Current employment status for partner/spouse] NVARCHAR(MAX),
    [H-CLIC 1.24 Is your gender the same as the sex you were registered at birth?] NVARCHAR(MAX),

    [H-CLIC 3.2 Support needs] NVARCHAR(MAX),

    [H-CLIC 4.2 Date prevention duty started] NVARCHAR(MAX),
    [H-CLIC 4.3 Prevention Activity undertaken] NVARCHAR(MAX),
    [H-CLIC 4.4 Were the applicants support needs engaged during the prevention stage?] NVARCHAR(MAX),
    [H-CLIC 4.5 Date Prevention Duty ended ] NVARCHAR(MAX),
    [H-CLIC 4.6 Reason Prevention Duty ended] NVARCHAR(MAX),
    [H-CLIC 4.7 Is a temporary accommodation duty owed following the end of the prevention duty] NVARCHAR(MAX),
    [H-CLIC 4.8 Applicant’s accommodation at point Prevention Duty ended] NVARCHAR(MAX),
    [H-CLIC 4.9 Which Local Authority area is this accommodation in?] NVARCHAR(MAX),

    [H-CLIC 5.2 Date Relief duty started] NVARCHAR(MAX),
    [H-CLIC 5.3 Relief Activity undertaken] NVARCHAR(MAX),
    [H-CLIC 5.4 Were the applicant’s support needs engaged during the prevention stage?] NVARCHAR(MAX),
    [H-CLIC 5.5 Date Relief Duty ended ] NVARCHAR(MAX),
    [H-CLIC 5.6 Reason Relief Duty ended] NVARCHAR(MAX),
    [H-CLIC 5.7 Is a temporary accommodation duty owed during the relief duty?] NVARCHAR(MAX),
    [H-CLIC 5.8 Applicant’s accommodation at point Relief Duty ended] NVARCHAR(MAX),
    [H-CLIC 5.9 Which Local Authority area is this accommodation in?] NVARCHAR(MAX),
    [H-CLIC 5.10 If referred to another Local Authority, which Local Authority?] NVARCHAR(MAX),

    [H-CLIC 6.2 Assistance with support needs] NVARCHAR(MAX),

    [H-CLIC 7.1 Main duty decision date] NVARCHAR(MAX),
    [H-CLIC 7.2 Date main duty decision takes effect ] NVARCHAR(MAX),
    [H-CLIC 7.3 The outcome of the decision issued on what duty (if any) is owed when relief stage ends (the main duty)] NVARCHAR(MAX),
    [H-CLIC 7.4 Was relief offered to legacy cases?] NVARCHAR(MAX),
    [H-CLIC 7.5 What priority need the applicant has?] NVARCHAR(MAX),
    [H-CLIC 7.6 Is a s193 Temporary Accommodation housing duty owed to the applicant?] NVARCHAR(MAX),
    [H-CLIC 7.7 What kind of accommodation is/was the applicant in when you brought the duty to an end?] NVARCHAR(MAX),
    [H-CLIC 7.8 Have you referred the main housing duty to another local authority?] NVARCHAR(MAX),
    [H-CLIC 7.9 In what local authority district is the accommodation outcome described in H-CLIC 7.7] NVARCHAR(MAX),

    [H-CLIC 8.2 Section 193(2), section 193C(4) or section 195A(1) duty end date] NVARCHAR(MAX),
    [H-CLIC 8.3 What is the reason the section 193(2) Duty, the section 193C(4) Duty or the section 195A(1) Duty has ended?] NVARCHAR(MAX),
    [H-CLIC 8.4 What was the applicant's accommodation when section 193(2), section 193C(4) or the section 195A(1) duty ended?] NVARCHAR(MAX),
    [H-CLIC 8.5 In what local authority district is the accommodation outcome?] NVARCHAR(MAX),

    [Hclic 9.2 Entry Date] NVARCHAR(MAX),
    [Hclic 9.3 Placement Entry Date] NVARCHAR(MAX),
    [Hclic 9.4 Placement Exit Date] NVARCHAR(MAX),
    [Hclic 9.5 TA Type] NVARCHAR(MAX),
    [Hclic 9.6 No Of Bedroom] NVARCHAR(MAX),
    [Hclic 9.7 Duty Provided] NVARCHAR(MAX),
    [Hclic 9.8 Duty Provided] NVARCHAR(MAX),
    [Hclic 9.9 Exit Date] NVARCHAR(MAX),

    [HCLIC 10.2 Review Start Date] NVARCHAR(MAX),
    [HCLIC 10.3 Review End Date] NVARCHAR(MAX),
    [HCLIC 10.4 Review Requested] NVARCHAR(MAX),
    [HCLIC 10.5 Review Appeal] NVARCHAR(MAX),
    [HCLIC 10.6 Review Outcome] NVARCHAR(MAX),

    [SecondAssignedOfficer] NVARCHAR(MAX)
    dwh_create_date DATETIME2 DEFAULT GETDATE()
);
GO
