/*
======================================================================
stored procedure: Load silver Layer ( Bronze - > Silver)
======================================================================
script purpose: 
  THIS STORED PROCEDURE performs the ETL (Extract, transformation, Load) process to populate the 'silver' schema tables from the 'bronze' schema'

Actions Performed:

- Truncate Silver tables.
- Inserts transformed and cleansed data from Bronze into Silver tables. 

Parameters: 
 None - this stored procedure does not accept any parameters or return any values. 

Use Example: 
 EXEC silver.load__silver_Hope;

========================================================================
*/








EXEC silver.load_silver



CREATE OR ALTER PROCEDURE silver.load_silver_Hope AS

BEGIN
    DECLARE @start_time DATETIME, @end_time DATETIME;
	BEGIN TRY
		PRINT '==============================================================';
		PRINT 'Loading silver Layer';
		PRINT '==============================================================';


		PRINT '==============================================================';
		PRINT 'Loading HopeExtract Table';
		PRINT '==============================================================';

	SET @start_time = GETDATE();
	PRINT '>> Truncating Table Into: [silver].[HopeExtract]';

	TRUNCATE TABLE [silver].[HopeExtract];

	PRINT '>> Inserting Data Into: silver.HopeExtract';

	INSERT INTO [silver].[HopeExtract] (
		[Application Id],
		[Household Id],
		[Person Id],
		[First Name],
		[Last Name HCLIC A1.5],
		[NINO HCLIC A1.6],
		[Email Address],
		[Mobile Number],
		[Date of Birth HCLIC A1.3],
		[Sex HCLIC 2.3],
		[Relationship HCLIC -2.5],
		[Age at Application(HCLIC - 2.4)],
		[Age on Quarter End(HCLIC -2.8)],
		[Date Of Submission],
		[Assigned To],
		[Date Joined(HCLIC -2.6)],
		[Address (HCLIC A1.7)],
		[PostCode (HCLIC A1.8)],
		[Address Type],
		[Date Move In],
		[Date Move Out],
		[App Type],
		[Plan Type],
		[Plan Created Date],
		[Plan Publish Status],
		[Is the applicant working?],
		[Has the applicant ever worked?],
		[Reason for no longer working],
		[What is the applicants average weekly hours and income?],
		[Has the applicant been granted refugee status in the uk?],
		[Has the applicant been given any leave to remain whether limited or Indefinite leave to remain with Recource to public funds?],
		[Is the applicant primary carer of a British national?],
		[Has the applicant got Indefinite or limited or Exceptional Leave to Enter or Remain in the UK with no immigration restrict],
		[Is the applicant self-employed?],
		[Has the applicant been posted here by an EU company on a temporary basis to provide services on behalf of an undertaking],
		[Reason why the applicant is not eligible?],
		[Is the applicant only in the UK as a job seeker?],
		[Worker - is the work genuine and effective and not marginal and ancillary?],
		[Reason for no longer working - Others],
		[What was the applicants average weekly hours and income?],
		[Worker - was the work genuine and effective and not marginal and ancillary?],
		[Is the applicant engaging in self-employment?],
		[Has the applicant ever been self-employed?],
		[Reason for no longer being self-employed],
		[What was the applicants average weekly hours & income?],
		[Self-employed - was the work genuine and effective and not marginal and ancillary?],
		[Applicant is the citizen of which country?],
		[Is the applicant Self sufficient with comprehensive sickness insurance?],
		[Is the applicant a student and self sufficient with comprehensive sickness insurance?],
		[Is the applicant a family member of an EEA national exercising their EU right in the UK],
		[Is the EEA national a worker or self employed?],
		[Is the EEA national a job seeker or self-sufficient?],
		[Does the applicant have a Derivative right?],
		[Does the applicant have a right to reside permanently in the UK?],
		[What is applicants average weekly hours and income?],
		[Worker: is the work genuine and effective and not marginal and ancillary?],
		[Reason for no longer being self-employed - Others],
		[Are they habitually resident in the UK?],
		[Please select the relationship?],
		[Please provide details of dependants],
		[What is the applicant average weekly hours and income?],
		[Is the work genuine and effective and not marginal and ancillary?],
		[Reason for no longer working or self-employed],
		[Reason for no longer working-Others],
		[What was the average weekly hours and income?],
		[Was the work genuine and effective and not marginal and ancillary?],
		[Please select the reason for Derivative right?],
		[Please select the reason for applicant's right to reside permanently in the UK?],
		[Did the applicant work lawfully in the UK for 12 months prior to 1 July 2013?],
		[Please select the relationship],
		[Please provide details of dependant's],
		[How long is the applicants most recent period of residence in the UK?],
		[Are they returning to resume a previous period of residence in the UK?],
		[Did the applicant enter the UK under the Highly Skilled Migrants programme and are Working?],
		[Did the applicant enter the UK as a low skill worker and are working in agriculture and food processing?],
		[Was the applicant a low skill worker and working in agriculture and food processing for 12 months?],
		[Is the applicant a family member of an EEA national exercising their EU right in the UK?],
		[Are you satisfied that the applicant is homeless?],
		[Being evicted by Housing Association (add details if this is a relevant issue)],
		[Being evicted by Council (add details if this is a relevant issue)],
		[Being evicted by Family / Friends (add details if this is a relevant issue)],
		[Being evicted by Private Landlord (add details if this is a relevant issue)],
		[Being evicted by resident landlord (add details if this is a relevant issue)],
		[Being evicted by employer (add details if this is a relevant issue)],
		[Overcrowded (add details if this is a relevant issue)],
		[Condition / disrepair (add details if this is a relevant issue)],
		[Threat of violence (add details if this is a relevant issue)],
		[Not affordable (add details if this is a relevant issue)],
		[Does the applicant have accommodation available to them in UK or elsewhere? ],
		[Medical issues (add details if this is a relevant issue)],
		[Other reason (add details if this is a relevant issue)],
		[Is the applicant being evicted from accommodation that is otherwise available and reasonable to continue to occupy?],
		[Pending leave date ],
		[Reason for leaving ],
		[Type of eviction],
		[Is the applicant or a member of the household currently at risk of abuse, violence or harassement?],
		[Name of the Victim],
		[Do they know the perpetrator?],
		[Name of Perpetrator],
		[Is this domestic violence from partner?],
		[Is this violence from outside the home?],
		[Does the applicant consider the accommodation reasonable to continue to occupy?],
		[Type of Violence / Harassment],
		[Does the authority consider the accommodation reasonable to continue to occupy?],
		[Does the applicant have to leave within 56 days?],
		[Has the applicant been served with a Section 21 notice within 56 days?],
		[Is the applicant withholding information in relation to their homelessness?],
		[If applicant does not feel accommodation is reasonable, what is the reason for this? ],
		[Please tell us why the accommodation is no longer available? ],
		[Officer's Decision: Reasonable accommodation?],
		[Reason for decision],
		[Before getting the s.21 notice, did the tenant make a complaint about the condition of the property to the landlord, in writing],
		[Does the S.21 notice form look exactly like the Form 6A here (or to substantially the same effect)],
		[Tenancy in a House of Multiple Occupation that requires licensing under Mandatory licensing, or the Local Authorities],
		[Was a deposit taken for the tenancy before 6 April 2007?],
		[Have there been any new tenancy agreements since 6 April 2007],
		[Has the deposit been protected in a deposit scheme?],
		[Was a deposit taken?],
		[Did current tenancy agreement start on or after 1 October 2015?],
		[Was the deposit protected in a scheme at any time and still protected? (if not paid back to tenant before s.21 notice)],
		[Was the ‘prescribed information’ given in full at any time?],
		[Is this the first tenancy agreement for the property?],
		[Was the deposit protected in a scheme within 30 days of being received?],
		[Was the deposit protected and prescribed information served during a previous tenancy agreement for the same property?],
		[Was the deposit protected and prescribed information served within 30 days of the deposit being taken?],
		[Was the deposit protected in an approved scheme within 30 days of being taken?],
		[Was the prescribed information given to the tenant before or at the same time as the section 21 notice],
		[Does the Section 21 Notice give at least two months notice AND date given is at end at or after the end of the fixed term?],
		[Does the Section 21 Notice give at least two months notice AND date given if is at end at or after the end of the fixed term?],
		[Has the tenant received: Gas safety certificate dated in last 12 months (if gas supply) Government ‘How to Rent’ Booklet?],
		[Is the tenancy of a room in a house in multiple occupation with shared facilities?],
		[Has the tenant received an energy Performance Certificate for the flat/house],
		[Was the section 21 notice served less than 4 months from the start of the tenancy],
		[Does it give at least 2 months notice?],
		[Was the section 21 notice served more than 6 months ago],
		[Has the Council served an Improvement Notice or Emergency Remedial Notice about the property in the last 6 months?],
		[Is a temporary accommodation duty owed during the prevention duty?],
		[Prevention Review Date],
		[Is the applicant failing to cooperate?],
		[Does the authority wish to end the prevention duty on the basis of ‘Refused to cooperate’?],
		[Has this decision been signed off by an appropriate person?],
		[PREV- Does the applicant agree with the plan?If yes,issue a prevention duty notification letter with a copy of the personal plan],
		[Please provide details of the appropriate person],
		[applicant disagrees with the plan? If no, issue a prevention duty notification letter with a copy of the personal plan],
		[Circumstances that caused the applicant to become homeless or threatened with homelessness],
		[Housing Needs of the applicant],
		[Housing Wishes of the applicant],
		[Support needs of the applicant to acquire and maintain accommodation],
		[Do you have reasons to believe the applicant is eligible?],
		[Please provide reasons to believe that applicant is eligible],
		[Do you have reasons to believe the applicant is Homeless?],
		[Please provide reasons to believe that applicant is Homeless],
		[Do you have reasons to believe that applicant has a priority need?],
		[Please provide reasons to believe that applicant has a priority need],
		[Temporary accommodation provided?],
		[Do you wish to make a final accommodation offer ],
		[Does the applicant consider the accommodation they have accepted unsuitable ],
		[Does the authority consider the accommodation suitable ],
		[Do you wish to make a final part 6 offer ],
		[Do you wish to end the relief duty because the applicant has refused a final part 6 offer ],
		[Does the authority wish to end the relief duty on the basis of refused to cooperate ],
		[Has this decision been signed off by an appropriate person],
		[please provide details of the appropriate person.],
		[Do you wish to end the relief duty because the applicant has refused a final accommodation offer],
		[Relief Review Date],
		[Does the applicant have any preference as to where they would like to live?],
		[Is there a particular type of accommodation will meet the applicant and his/her households needs?],
		[Supported Hostel],
		[REL- Does the applicant agree with the plan?],
		[If the applicant disagrees with the plan give reasons why],
		[Circumstances that caused the applicant to become homeless],
		[Housing Needs of the applicant.],
		[Housing Wishes of the applicant.],
		[Support needs of the applicant to acquire and maintain accommodation. ],
		[Does the applicant have residency in the district 6 out of the last 12 months or 3 out of the last 5 years?],
		[Give Details],
		[Is the applicant under 21 and is provided accommodation under section 22(a) of the Children Act 1989?],
		[Do they have a local connection with another Authority],
		[Please provide reason.],
		[Will they run the risk of violence in that district?],
		[Are you satisfied that the applicant is eligible for local connection?],
		[Please provide reason for local connection],
		[Is the applicant employed in the district],
		[Please provide reason for district?],
		[Does the applicant have family association living in the district in the last 5 years?],
		[Please provide reasons],
		[Does the applicant have any special circumstances?],
		[Please provide reason for special circumstances],
		[Is the applicant a duty under section 23(c) of the Children Act 1989],
		[Is the applicant in any of the priority need groups?],
		[Pregnancy - is the applicant or member of the household pregnant?],
		[Dependant children – below the age of 16 or aged 16-18, who is dependent and either normally resident],
		[16 and 17 year olds - Is there a child, 16 or 17 years old and who is not a ‘relevant child’ or a child in need],
		[looked after, accommodated or fostered - Applicant is not a person who is aged 18 to 20 and was formerly looked after],
		[Emergency - The Applicant is homeless because of an emergency such as fire, flood, or a similar disaster?],
		[Vulnerability - Applicant is vulnerable as the result of List following heading if relevant to QA],
		[Household intentionally homeless?],
		[Does the applicant feel that the accommodation was reasonable to continue to occupy],
		[Does the applicant feel that their actions were the result of inability to manage their own affairs or mental illness],
		[If the section 193a Temporary Accommodation duty is not owed, where is the applicant living?],
		[What was the applicant's accommodation when section 193(2), section 193C(4) or the section 195A(1) duty ended?],
		[Does the applicant have residency in the district 6 out of the last 12 months or 3 out of the last 5 years],
		[Please Give details],
		[applicant under 21 and is provided accommodation under section 22(a) Children Act 1989 and has resided for the last 2 years?],
		[Do they have a local connection with another authority?],
		[Please provide reason],
		[Will they run the risk of violence in that district],
		[Do you wish to refer the relief duty to another local authority?],
		[Are you satisfied that the applicant is eligible for local connection],
		[Please provide the reason],
		[Is the applicant employed in the district?],
		[Please provide a reason],
		[Does the applicant have family association living in the district?],
		[Please provide reason also.],
		[Does the applicant have any special circumstances],
		[Please provide reason for circumstances],
		[Is the applicant owed a duty under section 23(c) of the Children Act 1989?],
		[Household Member Description],
		[ApplicantÂ Date started],
		[ partner/spouse ApplicantÂ Date started],
		[Â partner/spouse Description ],
		[If unemployed, has the applicant or a member of the household ever worked in the UK?],
		[Enter dates last worked],
		[Date received],
		[Employment status of the main applicant],
		[Referred into another authority],
		[Does the applicant or a member of the household have any support needs?],
		[Does anyone help the person with their support needs?],
		[H-CLIC 1.1 Local Authority Code and Case Reference Number ],
		[H-CLIC 1.3 Are you satisfied that the applicant is eligible for assistance?],
		[H-CLIC 1.4 Number of Children],
		[H-CLIC 1.5 Date of assessment],
		[H-CLIC 1.6 What duties are owed to the applicant?],
		[H-CLIC 1.7 Ethnic Group of the main applicant],
		[H-CLIC 1.8 Sexual Preference of the main applicant],
		[H-CLIC 1.9 What is the nationality of the main applicant?],
		[H-CLIC 1.10 Current employment status for applicant],
		[H-CLIC 1.11 Is anyone in the household claiming benefits towards housing costs?],
		[H-CLIC 1.12 Is anyone in the household claiming benefits towards other living costs?],
		[H-CLIC 1.13 Please give details of current address],
		[H-CLIC 1.14 Last settled accommodation type],
		[H-CLIC 1.15 Main reason for loss of settled home],
		[H-CLIC 1.16 what was the reason for the loss of private tenancy (Assured Shorthold Tenancy)?],
		[H-CLIC 1.17 what was the reason for the loss of social rented tenancy?],
		[H-CLIC 1.18 what was the reason for the eviction from supported housing?],
		[H-CLIC 1.19 Whether applicant referred to the authority?],
		[H-CLIC 1.20 Agency type],
		[H-CLIC 1.21 Referred by another authority],
		[H-CLIC 1.22 Date homeless application made],
		[H-CLIC 1.23 Current employment status for partner/spouse],
		[H-CLIC 1.24 Is your gender the same as the sex you were registered at birth?],
		[H-CLIC 3.2 Support needs],
		[H-CLIC 4.2 Date prevention duty started],
		[H-CLIC 4.3 Prevention Activity undertaken],
		[H-CLIC 4.4 Were the applicants support needs engaged during the prevention stage?],
		[H-CLIC 4.5 Date Prevention Duty ended ],
		[H-CLIC 4.6 Reason Prevention Duty ended],
		[H-CLIC 4.7 Is a temporary accommodation duty owed following the end of the prevention duty],
		[H-CLIC 4.8 Applicant’s accommodation at point Prevention Duty ended],
		[H-CLIC 4.9 Which Local Authority area is this accommodation in?],
		[H-CLIC 5.2 Date Relief duty started],
		[H-CLIC 5.3 Relief Activity undertaken],
		[H-CLIC 5.4 Were the applicant’s support needs engaged during the prevention stage?],
		[H-CLIC 5.5 Date Relief Duty ended ],
		[H-CLIC 5.6 Reason Relief Duty ended],
		[H-CLIC 5.7 Is a temporary accommodation duty owed during the relief duty?],
		[H-CLIC 5.8 Applicant’s accommodation at point Relief Duty ended],
		[H-CLIC 5.9 Which Local Authority area is this accommodation in?],
		[H-CLIC 5.10 If referred to another Local Authority, which Local Authority?],
		[H-CLIC 6.2 Assistance with support needs],
		[H-CLIC 7.1 Main duty decision date],
		[H-CLIC 7.2 Date main duty decision takes effect ],
		[H-CLIC 7.3 The outcome of the decision issued on what duty (if any) is owed when relief stage ends (the main duty)],
		[H-CLIC 7.4 Was relief offered to legacy cases?],
		[H-CLIC 7.5 What priority need the applicant has?],
		[H-CLIC 7.6 Is a s193 Temporary Accommodation housing duty owed to the applicant?],
		[H-CLIC 7.7 What kind of accommodation is/was the applicant in when you brought the duty to an end?],
		[H-CLIC 7.8 Have you referred the main housing duty to another local authority?],
		[H-CLIC 7.9 In what local authority district is the accommodation outcome described in H-CLIC 7.7],
		[H-CLIC 8.2 Section 193(2), section 193C(4) or section 195A(1) duty end date],
		[H-CLIC 8.3 What is the reason the section 193(2) Duty, the section 193C(4) Duty or the section 195A(1) Duty has ended?],
		[H-CLIC 8.4 What was the applicant's accommodation when section 193(2), section 193C(4) or the section 195A(1) duty ended?],
		[H-CLIC 8.5 In what local authority district is the accommodation outcome?],
		[Hclic 9.2 Entry Date],
		[Hclic 9.3 Placement Entry Date],
		[Hclic 9.4 Placement Exit Date],
		[Hclic 9.5 TA Type],
		[Hclic 9.6 No Of Bedroom],
		[Hclic 9.7 Duty Provided],
		[Hclic 9.8 Duty Provided],
		[Hclic 9.9 Exit Date],
		[HCLIC 10.2 Review Start Date],
		[HCLIC 10.3 Review End Date],
		[HCLIC 10.4 Review Requested],
		[HCLIC 10.5 Review Appeal],
		[HCLIC 10.6 Review Outcome],
		[SecondAssignedOfficer])

		dwh_create_date DATETIME2 DEFAULT GETDATE()
)

	SELECT 
		CAST [Application Id] AS INT,
		CAST [Household Id] AS INT,
		CASE 
             WHEN COUNT([Household Id]) OVER (PARTITION BY [Household Id]) > 1 
            THEN 'Family'
            ELSE 'Single'
        END AS Household_TypeCAST  [Person Id]  AS INT,
		UPPER (TRIM [First Name]),
		UPPER (TRIM [Last Name HCLIC A1.5]),
		[NINO HCLIC A1.6],
		[Email Address],
		[Mobile Number],
		CAST [Date of Birth HCLIC A1.3] AS DATE,
		CASE UPPER(TRIM([Sex HCLIC 2.3])
			 WHEN 'FEMALE' THEN 'FEMALE'
			 WHEN 'MALE' THEN 'MALE'
			 WHEN 'UNSPECIFIED' THEN 'UNSPECIFIED'
			 ELSE 'UNSPECIFIED'
		END AS SEX,
		[Relationship HCLIC -2.5],
		CAST [Age at Application(HCLIC - 2.4)] AS INT),
		CAST [Age on Quarter End(HCLIC -2.8)] AS INT),
		CAST [Date Of Submission] AS DATE,
		[Assigned To],
		CAST [Date Joined(HCLIC -2.6)] AS DATE,
		[Address (HCLIC A1.7)],
		Trim([PostCode (HCLIC A1.8)]),
		[Address Type],
		CAST [Date Move In]  AS DATE,
		CAST [Date Move Out]  AS DATE,
		[App Type],
		[Plan Type],
		CAST [Plan Created Date] AS DATE,
		[Plan Publish Status],
		[Is the applicant working?],
		[Has the applicant ever worked?],
		[Reason for no longer working],
		[What is the applicants average weekly hours and income?],
		[Has the applicant been granted refugee status in the uk?],
		[Has the applicant been given any leave to remain whether limited or Indefinite leave to remain with Recource to public funds?],
		[Is the applicant primary carer of a British national?],
		[Has the applicant got Indefinite or limited or Exceptional Leave to Enter or Remain in the UK with no immigration restrict],
		[Is the applicant self-employed?],
		[Has the applicant been posted here by an EU company on a temporary basis to provide services on behalf of an undertaking],
		[Reason why the applicant is not eligible?],
		[Is the applicant only in the UK as a job seeker?],
		[Worker - is the work genuine and effective and not marginal and ancillary?],
		[Reason for no longer working - Others],
		[What was the applicants average weekly hours and income?],
		[Worker - was the work genuine and effective and not marginal and ancillary?],
		[Is the applicant engaging in self-employment?],
		[Has the applicant ever been self-employed?],
		[Reason for no longer being self-employed],
		[What was the applicants average weekly hours & income?],
		[Self-employed - was the work genuine and effective and not marginal and ancillary?],
		[Applicant is the citizen of which country?],
		[Is the applicant Self sufficient with comprehensive sickness insurance?],
		[Is the applicant a student and self sufficient with comprehensive sickness insurance?],
		[Is the applicant a family member of an EEA national exercising their EU right in the UK],
		[Is the EEA national a worker or self employed?],
		[Is the EEA national a job seeker or self-sufficient?],
		[Does the applicant have a Derivative right?],
		[Does the applicant have a right to reside permanently in the UK?],
		[What is applicants average weekly hours and income?],
		[Worker: is the work genuine and effective and not marginal and ancillary?],
		[Reason for no longer being self-employed - Others],
		[Are they habitually resident in the UK?],
		[Please select the relationship?],
		[Please provide details of dependants],
		[What is the applicant average weekly hours and income?],
		[Is the work genuine and effective and not marginal and ancillary?],
		[Reason for no longer working or self-employed],
		[Reason for no longer working-Others],
		[What was the average weekly hours and income?],
		[Was the work genuine and effective and not marginal and ancillary?],
		[Please select the reason for Derivative right?],
		[Please select the reason for applicant's right to reside permanently in the UK?],
		[Did the applicant work lawfully in the UK for 12 months prior to 1 July 2013?],
		[Please select the relationship],
		[Please provide details of dependant's],
		[How long is the applicants most recent period of residence in the UK?],
		[Are they returning to resume a previous period of residence in the UK?],
		[Did the applicant enter the UK under the Highly Skilled Migrants programme and are Working?],
		[Did the applicant enter the UK as a low skill worker and are working in agriculture and food processing?],
		[Was the applicant a low skill worker and working in agriculture and food processing for 12 months?],
		[Is the applicant a family member of an EEA national exercising their EU right in the UK?],
		[Are you satisfied that the applicant is homeless?],
		[Being evicted by Housing Association (add details if this is a relevant issue)],
		[Being evicted by Council (add details if this is a relevant issue)],
		[Being evicted by Family / Friends (add details if this is a relevant issue)],
		[Being evicted by Private Landlord (add details if this is a relevant issue)],
		[Being evicted by resident landlord (add details if this is a relevant issue)],
		[Being evicted by employer (add details if this is a relevant issue)],
		[Overcrowded (add details if this is a relevant issue)],
		[Condition / disrepair (add details if this is a relevant issue)],
		[Threat of violence (add details if this is a relevant issue)],
		[Not affordable (add details if this is a relevant issue)],
		[Does the applicant have accommodation available to them in UK or elsewhere? ],
		[Medical issues (add details if this is a relevant issue)],
		[Other reason (add details if this is a relevant issue)],
		[Is the applicant being evicted from accommodation that is otherwise available and reasonable to continue to occupy?],
		[Pending leave date ],
		[Reason for leaving ],
		[Type of eviction],
		[Is the applicant or a member of the household currently at risk of abuse, violence or harassement?],
		[Name of the Victim],
		[Do they know the perpetrator?],
		[Name of Perpetrator],
		[Is this domestic violence from partner?],
		[Is this violence from outside the home?],
		[Does the applicant consider the accommodation reasonable to continue to occupy?],
		[Type of Violence / Harassment],
		[Does the authority consider the accommodation reasonable to continue to occupy?],
		[Does the applicant have to leave within 56 days?],
		[Has the applicant been served with a Section 21 notice within 56 days?],
		[Is the applicant withholding information in relation to their homelessness?],
		[If applicant does not feel accommodation is reasonable, what is the reason for this? ],
		[Please tell us why the accommodation is no longer available? ],
		[Officer's Decision: Reasonable accommodation?],
		[Reason for decision],
		[Before getting the s.21 notice, did the tenant make a complaint about the condition of the property to the landlord, in writing],
		[Does the S.21 notice form look exactly like the Form 6A here (or to substantially the same effect)],
		[Tenancy in a House of Multiple Occupation that requires licensing under Mandatory licensing, or the Local Authorities],
		[Was a deposit taken for the tenancy before 6 April 2007?],
		[Have there been any new tenancy agreements since 6 April 2007],
		[Has the deposit been protected in a deposit scheme?],
		[Was a deposit taken?],
		[Did current tenancy agreement start on or after 1 October 2015?],
		[Was the deposit protected in a scheme at any time and still protected? (if not paid back to tenant before s.21 notice)],
		[Was the ‘prescribed information’ given in full at any time?],
		[Is this the first tenancy agreement for the property?],
		[Was the deposit protected in a scheme within 30 days of being received?],
		[Was the deposit protected and prescribed information served during a previous tenancy agreement for the same property?],
		[Was the deposit protected and prescribed information served within 30 days of the deposit being taken?],
		[Was the deposit protected in an approved scheme within 30 days of being taken?],
		[Was the prescribed information given to the tenant before or at the same time as the section 21 notice],
		[Does the Section 21 Notice give at least two months notice AND date given is at end at or after the end of the fixed term?],
		[Does the Section 21 Notice give at least two months notice AND date given if is at end at or after the end of the fixed term?],
		[Has the tenant received: Gas safety certificate dated in last 12 months (if gas supply) Government ‘How to Rent’ Booklet?],
		[Is the tenancy of a room in a house in multiple occupation with shared facilities?],
		[Has the tenant received an energy Performance Certificate for the flat/house],
		[Was the section 21 notice served less than 4 months from the start of the tenancy],
		[Does it give at least 2 months notice?],
		[Was the section 21 notice served more than 6 months ago],
		[Has the Council served an Improvement Notice or Emergency Remedial Notice about the property in the last 6 months?],
		[Is a temporary accommodation duty owed during the prevention duty?],
		[Prevention Review Date],
		[Is the applicant failing to cooperate?],
		[Does the authority wish to end the prevention duty on the basis of ‘Refused to cooperate’?],
		[Has this decision been signed off by an appropriate person?],
		[PREV- Does the applicant agree with the plan?If yes,issue a prevention duty notification letter with a copy of the personal plan],
		[Please provide details of the appropriate person],
		[applicant disagrees with the plan? If no, issue a prevention duty notification letter with a copy of the personal plan],
		[Circumstances that caused the applicant to become homeless or threatened with homelessness],
		[Housing Needs of the applicant],
		[Housing Wishes of the applicant],
		[Support needs of the applicant to acquire and maintain accommodation],
		[Do you have reasons to believe the applicant is eligible?],
		[Please provide reasons to believe that applicant is eligible],
		[Do you have reasons to believe the applicant is Homeless?],
		[Please provide reasons to believe that applicant is Homeless],
		[Do you have reasons to believe that applicant has a priority need?],
		[Please provide reasons to believe that applicant has a priority need],
		[Temporary accommodation provided?],
		[Do you wish to make a final accommodation offer ],
		[Does the applicant consider the accommodation they have accepted unsuitable ],
		[Does the authority consider the accommodation suitable ],
		[Do you wish to make a final part 6 offer ],
		[Do you wish to end the relief duty because the applicant has refused a final part 6 offer ],
		[Does the authority wish to end the relief duty on the basis of refused to cooperate ],
		[Has this decision been signed off by an appropriate person],
		[please provide details of the appropriate person.],
		[Do you wish to end the relief duty because the applicant has refused a final accommodation offer],
		[Relief Review Date],
		[Does the applicant have any preference as to where they would like to live?],
		[Is there a particular type of accommodation will meet the applicant and his/her households needs?],
		[Supported Hostel],
		[REL- Does the applicant agree with the plan?],
		[If the applicant disagrees with the plan give reasons why],
		[Circumstances that caused the applicant to become homeless],
		[Housing Needs of the applicant.],
		[Housing Wishes of the applicant.],
		[Support needs of the applicant to acquire and maintain accommodation. ],
		[Does the applicant have residency in the district 6 out of the last 12 months or 3 out of the last 5 years?],
		[Give Details],
		[Is the applicant under 21 and is provided accommodation under section 22(a) of the Children Act 1989?],
		[Do they have a local connection with another Authority],
		[Please provide reason.],
		[Will they run the risk of violence in that district?],
		[Are you satisfied that the applicant is eligible for local connection?],
		[Please provide reason for local connection],
		[Is the applicant employed in the district],
		[Please provide reason for district?],
		[Does the applicant have family association living in the district in the last 5 years?],
		[Please provide reasons],
		[Does the applicant have any special circumstances?],
		[Please provide reason for special circumstances],
		[Is the applicant a duty under section 23(c) of the Children Act 1989],
		[Is the applicant in any of the priority need groups?],
		[Pregnancy - is the applicant or member of the household pregnant?],
		[Dependant children – below the age of 16 or aged 16-18, who is dependent and either normally resident],
		[16 and 17 year olds - Is there a child, 16 or 17 years old and who is not a ‘relevant child’ or a child in need],
		[looked after, accommodated or fostered - Applicant is not a person who is aged 18 to 20 and was formerly looked after],
		[Emergency - The Applicant is homeless because of an emergency such as fire, flood, or a similar disaster?],
		[Vulnerability - Applicant is vulnerable as the result of List following heading if relevant to QA],
		[Household intentionally homeless?],
		[Does the applicant feel that the accommodation was reasonable to continue to occupy],
		[Does the applicant feel that their actions were the result of inability to manage their own affairs or mental illness],
		[If the section 193a Temporary Accommodation duty is not owed, where is the applicant living?],
		[What was the applicant's accommodation when section 193(2), section 193C(4) or the section 195A(1) duty ended?],
		[Does the applicant have residency in the district 6 out of the last 12 months or 3 out of the last 5 years],
		[Please Give details],
		[applicant under 21 and is provided accommodation under section 22(a) Children Act 1989 and has resided for the last 2 years?],
		[Do they have a local connection with another authority?],
		[Please provide reason],
		[Will they run the risk of violence in that district],
		[Do you wish to refer the relief duty to another local authority?],
		[Are you satisfied that the applicant is eligible for local connection],
		[Please provide the reason],
		[Is the applicant employed in the district?],
		[Please provide a reason],
		[Does the applicant have family association living in the district?],
		[Please provide reason also.],
		[Does the applicant have any special circumstances],
		[Please provide reason for circumstances],
		[Is the applicant owed a duty under section 23(c) of the Children Act 1989?],
		[Household Member Description],
		[ApplicantÂ Date started],
		[ partner/spouse ApplicantÂ Date started],
		[Â partner/spouse Description ],
		[If unemployed, has the applicant or a member of the household ever worked in the UK?],
		[Enter dates last worked],
		[Date received],
		[Employment status of the main applicant],
		[Referred into another authority],
		[Does the applicant or a member of the household have any support needs?],
		[Does anyone help the person with their support needs?],
		[H-CLIC 1.1 Local Authority Code and Case Reference Number ],
		[H-CLIC 1.3 Are you satisfied that the applicant is eligible for assistance?],
		CAST [H-CLIC 1.4 Number of Children] AS INT),
		CAST [H-CLIC 1.5 Date of assessment] AS DATE,
		[H-CLIC 1.6 What duties are owed to the applicant?],
		[H-CLIC 1.7 Ethnic Group of the main applicant],
		[H-CLIC 1.8 Sexual Preference of the main applicant],
		[H-CLIC 1.9 What is the nationality of the main applicant?],
		[H-CLIC 1.10 Current employment status for applicant],
		[H-CLIC 1.11 Is anyone in the household claiming benefits towards housing costs?],
		[H-CLIC 1.12 Is anyone in the household claiming benefits towards other living costs?],
		[H-CLIC 1.13 Please give details of current address],
		[H-CLIC 1.14 Last settled accommodation type],
		[H-CLIC 1.15 Main reason for loss of settled home],
		[H-CLIC 1.16 what was the reason for the loss of private tenancy (Assured Shorthold Tenancy)?],
		[H-CLIC 1.17 what was the reason for the loss of social rented tenancy?],
		[H-CLIC 1.18 what was the reason for the eviction from supported housing?],
		[H-CLIC 1.19 Whether applicant referred to the authority?],
		[H-CLIC 1.20 Agency type],
		[H-CLIC 1.21 Referred by another authority],
		CAST [H-CLIC 1.22 Date homeless application made] AS DATE,
		[H-CLIC 1.23 Current employment status for partner/spouse],
		[H-CLIC 1.24 Is your gender the same as the sex you were registered at birth?],
		[H-CLIC 3.2 Support needs],
		CAST [H-CLIC 4.2 Date prevention duty started] AS DATE,
		[H-CLIC 4.3 Prevention Activity undertaken],
		[H-CLIC 4.4 Were the applicants support needs engaged during the prevention stage?],
		CAST [H-CLIC 4.5 Date Prevention Duty ended ] AS DATE,
		[H-CLIC 4.6 Reason Prevention Duty ended],
		[H-CLIC 4.7 Is a temporary accommodation duty owed following the end of the prevention duty],
		[H-CLIC 4.8 Applicant’s accommodation at point Prevention Duty ended],
		[H-CLIC 4.9 Which Local Authority area is this accommodation in?],
		CAST [H-CLIC 5.2 Date Relief duty started] AS DATE,
		[H-CLIC 5.3 Relief Activity undertaken],
		[H-CLIC 5.4 Were the applicant’s support needs engaged during the prevention stage?],
		CAST [H-CLIC 5.5 Date Relief Duty ended ] AS DATE,
		CAST [H-CLIC 5.6 Reason Relief Duty ended] AS DATE,
		[H-CLIC 5.7 Is a temporary accommodation duty owed during the relief duty?],
		[H-CLIC 5.8 Applicant’s accommodation at point Relief Duty ended],
		[H-CLIC 5.9 Which Local Authority area is this accommodation in?],
		[H-CLIC 5.10 If referred to another Local Authority, which Local Authority?],
		[H-CLIC 6.2 Assistance with support needs],
		CAST [H-CLIC 7.1 Main duty decision date] AS DATE,
		CAST [H-CLIC 7.2 Date main duty decision takes effect ] AS DATE,
		[H-CLIC 7.3 The outcome of the decision issued on what duty (if any) is owed when relief stage ends (the main duty)],
		[H-CLIC 7.4 Was relief offered to legacy cases?],
		[H-CLIC 7.5 What priority need the applicant has?],
		[H-CLIC 7.6 Is a s193 Temporary Accommodation housing duty owed to the applicant?],
		[H-CLIC 7.7 What kind of accommodation is/was the applicant in when you brought the duty to an end?],
		[H-CLIC 7.8 Have you referred the main housing duty to another local authority?],
		[H-CLIC 7.9 In what local authority district is the accommodation outcome described in H-CLIC 7.7],
		CAST [H-CLIC 8.2 Section 193(2), section 193C(4) or section 195A(1) duty end date] AS DATE,
		[H-CLIC 8.3 What is the reason the section 193(2) Duty, the section 193C(4) Duty or the section 195A(1) Duty has ended?],
		[H-CLIC 8.4 What was the applicant's accommodation when section 193(2), section 193C(4) or the section 195A(1) duty ended?],
		[H-CLIC 8.5 In what local authority district is the accommodation outcome?],
		CAST [Hclic 9.2 Entry Date] AS DATE,
		CAST [Hclic 9.3 Placement Entry Date] AS DATE,
		CAST [Hclic 9.4 Placement Exit Date] AS DATE,
		[Hclic 9.5 TA Type],
		CAST [Hclic 9.6 No Of Bedroom] AS INT,
		[Hclic 9.7 Duty Provided],
		[Hclic 9.8 Duty Provided],
		CAST [Hclic 9.9 Exit Date] AS DATE,
		CAST [HCLIC 10.2 Review Start Date] AS DATE,
		CAST [HCLIC 10.3 Review End Date] AS DATE,
		[HCLIC 10.4 Review Requested],
		[HCLIC 10.5 Review Appeal],
		[HCLIC 10.6 Review Outcome],
		[SecondAssignedOfficer]),
		dwh_create_date DATETIME2 DEFAULT GETDATE()
	From Hope_bronze

		SET @end_time = GETDATE();
		PRINT '>> Load Duration: ' +CAST(DATEDIFF(SECOND,@start_time, @end_time) as NVARCHAR) + ' seconds';
		PRINT '================================'

END TRY
BEGIN CATCH
  PRINT '==============================='
  PRINT 'ERROR OCCURED DURING LOADING SILVER LAYER'
  PRINT 'Error Message' + ERROR_MESSAGE();
  PRINT  'Error Message' + CAST (ERROR_NUMBER () AS NVARCHAR);
  PRINT  'Error Message' + CAST (ERROR_SATE () AS NVARCHAR);
End CATCH
END
